home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^research/', include('research.urls', namespace="research")),
    url(r'^music/', include('music.urls', namespace="music")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'', include('home.urls', namespace="home")),
    url(r'^admin/', admin.site.urls)
]

projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^parser/$', views.parser, name='parser'),
]

research/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.research, name='index'),
]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

music/models.py
from __future__ import unicode_literals

from django.utils.encoding import python_2_unicode_compatible
from django.db import models

@python_2_unicode_compatible
class Composition(models.Model):
    title = models.CharField(max_length=200)
    code = models.CharField(max_length=200)

    def __str__(self):
        return self.title

projects/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Polynomial(models.Model):
    polynomial = models.CharField(max_length=500, null=True)

    def __str__(self):
        return self.polynomial

research/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

import re

@python_2_unicode_compatible
class Coauthor(models.Model):
    coauthor = models.CharField(max_length=500)
    institution = models.CharField(max_length=500)
    address = models.CharField(max_length=500)

    def __str__(self):
        return self.coauthor

@python_2_unicode_compatible
class Paper(models.Model):
    doi = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(max_length=500)
    coauthors = models.ManyToManyField(Coauthor, blank=True)
    publish_date = models.DateField('date published', blank=True, null=True)
    address = models.URLField(max_length=200)

    def __str__(self):
        return self.title

    def get_short_title(self):
        short = self.title.lower().split()[0]
        return re.sub(r'\W+', '', short)
        

projects/forms.py
import re
from . import polynomial_parser
from django import forms


bracket_re = re.compile("\([^\(]+?\)")
IMPOSSIBLES = {"++", "--", "**(", "xx",}
IMPOSSIBLES |= set("{}x".format(i) for i in range(10))
IMPOSSIBLES |= set("x{}".format(i) for i in range(10))
ALLOWED = {"1", "2", "3", "4", "5", "6", "7", "8", "9",
           "0", "x", "+", "*", " ", "-", "(", ")",}


class PolynomialForm(forms.Form):
    poly = forms.CharField(required=True,
                           error_messages={'required': "Please type something"})

    def clean(self):
        cleaned_data = super(PolynomialForm, self).clean()
        poly = cleaned_data.get("poly")

        d = {"(": 1, ")": -1}
        count = 0



        if not poly:
            return self.cleaned_data
        if "()" in poly:
            raise forms.ValidationError("Invalid format")
        for character in poly:
            try:
                if character not in ALLOWED:
                    raise forms.ValidationError("Invalid character: {}".format(
                    character))
            except UnicodeEncodeError:
                raise forms.ValidationError("Invalid format")
            count += d.get(character, 0)
            if count < 0:
                raise forms.ValidationError("Invalid bracketing")
        for substring in IMPOSSIBLES:
            if substring in poly:
                raise forms.ValidationError("Invalid format")
        if count:
            raise forms.ValidationError("Invalid bracketing")

        try:
            polynomial_parser.simplify(poly)
        except (IndexError, ValueError):
            raise forms.ValidationError("Invalid format")

        return self.cleaned_data

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'home/index.html', {})

music/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Composition


def index(request):
    pieces = Composition.objects.all()
    context = {"pieces": pieces}
    return render(request, 'music/index.html', context)

projects/views.py
from django.shortcuts import render, redirect
from forms import PolynomialForm
from django.forms import ValidationError
from . import polynomial_parser

from models import Polynomial

#
# def parser(request):
#     user_typed = None
#     standard_form = None
#     queryset = Polynomial.objects.all()
#
#     if queryset.exists():
#         p = queryset.first()
#         user_typed = p.polynomial
#         try:
#             standard_form = polynomial_parser.simplify(user_typed)
#         except ValueError:
#             pass
#         queryset.delete()
#         return render(request, 'projects/parser.html',
#                       {"user_typed": user_typed,
#                        "standard_form": standard_form})
#
#     if request.method == "POST":
#         p = Polynomial()
#         p.polynomial = request.POST['poly']
#         p.save()
#         return redirect('projects:parser')
#
#     return render(request, 'projects/parser.html', {})


def index(request):
    return render(request, 'projects/index.html', {})


def parser(request):

    poly = None
    form = PolynomialForm()

    if request.method == "POST":
        form = PolynomialForm(request.POST)
        if form.is_valid():
            try:
                request.session['poly'] = polynomial_parser.simplify(
                    form.cleaned_data['poly'])
            except IndexError:
                raise ValidationError("fart")

            return redirect('projects:parser')

    if 'poly' in request.session:
        poly = request.session['poly']
        del request.session['poly']

    return render(request, 'projects/parser.html', {'poly': poly,
                                                    'form': form,
                                                    'request': request})

research/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Paper, Coauthor

def research(request):
    latest_papers = Paper.objects.order_by('publish_date')
    context = {'latest_papers': latest_papers,
    }
    return render(request, 'research/index.html', context)

home/templates/home/index.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
<link rel="stylesheet" type="text/css"
      href="{%  static 'home/style.css' %}"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Paul Slevin's Website</title>
</head>
<body>
<div id="wrapper">
    <div id="headline">
        <div class="container">
            <h1>
                Paul Slevin
            </h1>
            <p>
                Welcome to my website!
            </p>
        </div>
    </div>
    <div id="about">
        <script type="text/javascript" async>
            var headlineheight = document.getElementById("headline").clientHeight;
            var fullLength = document.getElementsByTagName("html")[0].clientHeight;
            var middle = document.getElementById('about');
            var difference = fullLength-headlineheight;
            middle.style.minHeight = "calc("+difference+"px - 3em - 20px)";
        </script>
        <div class="container">
            <h2>
                About Me
            </h2>
            <img id="mepic" src="{% static 'home/paul2.jpg' %}" alt="Paul Slevin"/>

            <p>I am a programmer, a mathematician and a musician.</p>

             <div id="links">
                <a href="{% static 'home/cv2.pdf' %}" target="_blank">Download my CV</a>
            </div>

            <p>I am currently studying for a PhD in Mathematics at the University of Glasgow.</p>
            <p>
                Click the following links to find out more.
            </p>
                <div id="links">
                    <a href="{% url 'projects:index' %}">Projects</a>
                    <a href="{% url 'research:index' %}">Research</a>
                    <a href="{% url 'music:index' %}">Music</a>
                </div>
            <p id="last"><br/></p>
        </div>
    </div>
    <div id="footer">
        <div class="container">
            <p>
                This site is powered by Django.
            </p>
        </div>
    </div>
</div>



</body>
</html>

music/templates/music/index.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
<link rel="stylesheet" type="text/css"
      href="{%  static 'music/index.css' %}"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Music</title>
</head>

<div id="wrapper">
<div id="about">
<div class="container">
        <h2>My Music</h2>
        <p>
Here you can find
a selection of my musical compositions.
        </p>
        <p>Each link
will open up an embedded YouTube video for you to listen to.
        </p>



{% if pieces %}


    {% for p in pieces %}
        <div>
        <a class="musiclink" href="http://www.youtube.com/embed/{{ p.code }}"
        target="video" onclick="test();return true">
        {{ p.title }}
        </a>
        </div>
    {% endfor %}


{% else %}
    <p>No compositions are available.</p>
{% endif %}

<p>Click <a id="youtube" target="_blank" href="https://www.youtube.com/user/slevvio/videos">here</a> if you
would like to visit my YouTube channel!</p>
</div>
</div>

<div id="music">
<div class="container" id="y">
<iframe frameborder="0" allowfullscreen
 name="video"></iframe>
    <script type="text/javascript" async>
        var f = document.getElementsByTagName("iframe")[0]
        var w = document.getElementById("y").clientWidth;
        var h = 0.562 * w;
        f.style.height = h+"px";
    </script>
</div>
</div>

<div id="footer">
    <div class="container">
         <p>   <a href="{% url 'home:index' %}">Home</a>
            | <a href="{% url 'projects:index' %}">Projects</a>
            | <a href="{% url 'research:index' %}">Research</a>
            | <a href="{% url 'music:index' %}">Music</a></p>
    </div>
</div>
</div>
</html>

projects/templates/projects/index.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
<link rel="stylesheet" type="text/css"
      href="{%  static 'projects/style.css' %}"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Projects</title>
</head>
<body>
<div id="wrapper">
    <div id="about"><div class="container">
    <h2> My Projects</h2>

    <p>
        Here you can have a look at the Python projects
        I have been working on recently.
    </p>
    <div id="chat">
    <h3>
        <span>Polynomial parser</span>
    </h3>

    <p>
        I wrote a program for parsing polynomials!</p> <p>Click
        <a href="{% url 'projects:parser' %}">here</a> to try it, and
        click <a  target="_blank"
            href="https://github.com/paulslevin/projects/blob/master/checkio/polynomial_parser.py">here</a> for the source
        code.
    </p>
    <br/>
    <h3>
        <span>GitHub</span>
    </h3>

    <p>
        Click
        <a target=_blank" href="http://github.com/paulslevin/projects"> here</a>
        to see my GitHub repository.</p><p> Here you
            can find my
            solutions to various exercises from
        <a target=_blank" href="http://checkio.org">
           checkio.org</a>.</p><p> You can also see programs I wrote while taking part in the Python
        <a target=_blank" href="https://www.coursera.org/specializations/fundamentalscomputing2">
            Coursera</a> courses.
    </p>
    <br/>
    <h3>
        <span>
    This website!</span>
    </h3>

    <p>
        I developed the website you are currently visiting using Python and the
        <a target=_blank" href="http://djangoproject.com">Django</a> Web framework.</p><p>
        I designed it from scratch using CSS, HTML and Javascript. </p><p>
        The site design scales to any device!
        You can view the source code <a target="_blank" href="http://github.com/paulslevin/personal">here</a>.

    </p>
    <br/>
    <br/>
    </div></div></div>
    <div id="footer">
    <div class="container">
        <p><a href="{% url 'home:index' %}">Home</a>
            | <a href="{% url 'projects:index' %}">Projects</a>
            | <a href="{% url 'research:index' %}">Research</a>
            | <a href="{% url 'music:index' %}">Music</a></p></div>
</div>
</div>
</body>
</html>

projects/templates/projects/parser.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
<link rel="stylesheet" type="text/css"
      href="{%  static 'projects/parser.css' %}"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Parser</title>
</head>
<body>
<div id="wrapper">
<div id="about">
<div class="container">
<h2>Polynomial Parser</h2>
<p>
  This application converts a valid polynomial expression to standard form. See
  <a href="#terminology">below</a> for details of the terminology.
  Just type a string in the box and hit Enter. This parser is kind and allows you to
  include spaces.
</p>

{% if poly %}
    <p id="yay">You typed: <code>{{ poly }}</code></p>
{% endif %}
<form method="post">
    {% if form.non_field_errors %}
        <p id="error">{{ form.non_field_errors.0 }}</p>
    {% elif 'next' not in request.GET and not poly %}
        <p id="notyet">Go ahead, type something!</p>
    {% endif %}
{% csrf_token %}
{{ form.as_p }}
</form>
</div>
</div>

<div id="terminology">
{#    <script type="text/javascript" async>#}
{#            var headlineheight = document.getElementById("about").clientHeight;#}
{#            var fullLength = document.getElementsByTagName("html")[0].innerHTML.length;#}
{#            var middle = document.getElementById('terminology');#}
{#            var difference = fullLength-headlineheight;#}
{#            middle.style.minHeight = "calc("+difference+"px - 3em - 40px - 41.5px -3em)";#}
{#        </script>#}
<div class="container">
<h2>Terminology</h2>

  <div class="definition">
  <strong>Definition: </strong>A <em>valid</em>
  <a target="_blank" href="https://en.wikipedia.org/wiki/Polynomial">
    polynomial</a>
  expression is a string containing the characters
  <pre>+ - 0 1 2 3 4 5 6 7 8 9 ( ) * x</pre>
  representing a polynomial in <code>x</code> such that the bracketing is correct.
  We also require that any indices are given as positive integers, with no extra
  formatting.
    </div>
    <p>
    For example,
    </p>
  <pre>(9*x+5)**6*(3+x)*2
x**10+(1+5*x+3)**5+x**2</pre>
  <p>are both valid polynomials, but</p>
  <pre>x**0.5
x**(3-2)</pre>
  <p>are not.
</p>
<div class="definition" id="final">
<strong>Definition: </strong>A polynomial is in <em>standard form</em> if it looks like
<pre>
a_n*x**n+...+a_2*x**2+a_1*x+a_0
</pre>
for some number <code>n</code> and numbers <code>a_n,...,a_0</code>.
</div>
</div>
</div>

<div id="footer">
    <div class="container">
         <p>   <a href="{% url 'home:index' %}">Home</a>
            | <a href="{% url 'projects:index' %}">Projects</a>
            | <a href="{% url 'research:index' %}">Research</a>
            | <a href="{% url 'music:index' %}">Music</a></p>
    </div>
</div>
</div>
</body>
</html>

research/templates/research/index.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
<link rel="stylesheet" type="text/css"
      href="{%  static 'research/index.css' %}"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Research</title>
</head>
<body>
<div id="wrapper">
<div id="about">
{#    <script type="text/javascript" async>#}
{#            var headlineheight = document.getElementById("headline").clientHeight;#}
{#            var fullLength = document.getElementsByTagName("html")[0].clientHeight;#}
{#            var middle = document.getElementById('about');#}
{#            var difference = fullLength-headlineheight;#}
{#            middle.style.minHeight = "calc("+difference+"px - 3em - 20px)";#}
{#        </script>#}
    <div class="container">
        <h2>My Research</h2>
        <p>
Here you can find
a list of my published mathematical research.
        </p>
        <p>Each link
will take you to an online version of each work.
        </p>
        <p>They are
listed in chronological order of publication.
        </p>
        <p>
            {% for paper in latest_papers %}
                <a target ="_blank" href="{{ paper.address }}">{{ paper.title }}</a>
            {% endfor %}
        </p>
    <br/>
    </div>
</div>
<div id="footer">
    <div class="container">
        <p>   <a href="{% url 'home:index' %}">Home</a>
            | <a href="{% url 'projects:index' %}">Projects</a>
            | <a href="{% url 'research:index' %}">Research</a>
            | <a href="{% url 'music:index' %}">Music</a></p>
    </div>
</div>
</div>
</body>
</html>